name: Test
description: test

body:
  - type: dropdown
    id: is-blocker
    attributes:
      label: Is it a blocker for you?
      options:
        - 'Yes'
        - 'No'
        - 'Will be in the future'
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
    validations:
      required: true
    placeholder: |
      What behavior did you observe when encountering this issue?
      What behavior did you expect to observe?
      Is this a blocking issue with no known work-arounds?

  - type: input
    id: reproduction
    attributes:
      label: Please provide a link to a minimal reproduction of the bug

  - type: textarea
      id: exception-or-error
      attributes:
        label: Source code
        render: true
      placeholder: |
        ```chapel
        // Please provide source code that will reproduce the problem.
        // You can insert your code inline if it's not too long.
        // Otherwise, you can attach it as a file or provide a URL to it.
        // To the extent possible, providing simplified programs demonstrating the
        // problem will be appreciated.
        // You can also replace this section with "Associated Future Test(s)" below.
        ```
